### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Tomoya-Sonok** [Tomoya-Sonok/chat-space#9]
# IPアドレス
18.178.222.209

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①メッセージと画像を同時に投稿すると、メッセージがundefinedになってしまう
[![Image from Gyazo](https://i.gyazo.com/085419b230ee09fc1b2deea260205d86.png)](https://gyazo.com/085419b230ee09fc1b2deea260205d86)

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Tomoya-Sonok** [comment]
確認ありがとうございます！
修正いたしました！

**Comment by naru6117** [comment]
早速のご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by Tomoya-Sonok** [comment]
ありがとうございます！
個人アプリ制作も引き続き頑張ります！
